#!/bin/bash

echo ""
echo " Find matches with httpx by B4GG3R"
echo " Usage: matchfinder urls.txt 'stringtofind'"
echo ""

cat $1 | httpx -silent -match-regex $2

# For automating to multiple url list use this command:
# for a in $(ls | sort -u); do matchfinder $a 'stringtofind' ; done
